name: Deploy to GitHub Pages

on:
  push:
    branches: [primary]
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  # Build Artifact job
  build:
    name: Build Project
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: "Tar files"
        run: cd dist && tar -cvf ../twintails_color-calc-vue.tar ./color-calc-vue

      - name: Upload tar-tifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-color-calc-vue
          path: twintails_color-calc-vue.tar

      - name: Download tar-tifact
        uses: actions/download-artifact@v5
        with:
          name: gh-pages-color-calc-vue

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: gh-pages-color-calc-vue

      - name: Output deployment URL
        run: |
            echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

